### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by LazyFalcon** [LazyFalcon/Manipulator3D#1]
Dof:
https://www.opengl.org/discussion_boards/showthread.php/179209-Deferred-Rendering-Depth-of-Field-Blur
http://gpupro.blogspot.fi/2013/09/gpu-pro-4-skylanders-depth-of-field.html
http://devlog-martinsh.blogspot.fi/2011/11/glsl-depth-of-field-with-bokeh-v21.html
https://books.google.fi/books?id=_FnSBQAAQBAJ&pg=PA177&lpg=PA177&dq=Signed+CoC+radius&source=bl&ots=1OZGXswEVF&sig=cdmzO6sI1ZSoVudgK7J03ryZw7w&hl=pl&sa=X&ei=UNiHVb-rDsSJygOPipGIAQ&ved=0CCIQ6AEwAA#v=onepage&q=Signed%20CoC%20radius&f=false
http://http.developer.nvidia.com/GPUGems3/gpugems3_ch28.html
http://www.gamedev.net/topic/666059-technical-papers-on-real-time-rendering/?hl=%2Bdepth+%2Bof+%2Bfield#entry5212681
CoC: http://www.gamedev.net/topic/657920-depth-of-field-coc-questions/?hl=%2Bdepth+%2Bof+%2Bfield#entry5161816

blur:
https://software.intel.com/en-us/blogs/2014/07/15/an-investigation-of-fast-real-time-gpu-based-image-blur-algorithms

Explosions:
http://gpupro.blogspot.fi/2014/12/realistic-volumetric-explosions-in-games.html

Scattering:
http://gpupro.blogspot.fi/2014/01/gpu-pro-5-high-performance-outdoor.html

**Comment by DezerteR** [comment]
Eizo Foris FS2434

**Comment by DezerteR** [comment]
GCC ABI:
http://fedoramagazine.org/gcc-5-in-fedora-whats-an-abi-and-what-happens-when-we-change-it/

**Comment by DezerteR** [comment]
PBR:
https://www.marmoset.co/toolbag/learn/pbr-theory
https://www.reddit.com/r/starcitizen/comments/1rl7bq/could_somebody_please_explain_physical_based/

**Comment by DezerteR** [comment]
Normal mapping without tangents
http://www.thetenthplanet.de/archives/1180

**Comment by DezerteR** [comment]
http://www.xrite.com/online-color-test-challenge

**Comment by DezerteR** [comment]
Acceleration/decelaeration on hermite curve
http://stackoverflow.com/questions/3367308/math-ease-in-ease-out-a-displacement-using-hermite-curve-with-time-constraint
