### ISSUE TITLE
Collision avoidance

### ISSUE THREAD

**Issue by LazyFalcon** [LazyFalcon/Manipulator3D#14]
_PL_
Tak więc przydałoby się to zrobić, jakie ficzerki byłyby fajne
- omijanie przeszkód przez samą trasę, A*-based, podobnie jak w inżynierce, wprowadzić do tego trochę usprawnień
- customowe reakcje na kolizje, do wyboru: zatrzymać się, ominąć, wrócić na jakąś pozycję, lambda
- odsuwanie się robota od przeszkód, pojedynczy przypadek przeszkody-robot, wyznaczyć taką pozycję która jest bezkolizyjna, nie zważać na zadaną trasę, następnie znaleźć bezkolizyjną w pewnej odległości, cofnąć się kawałek i objechać przeszkodę. Można by to zrobić jakoś na sposób JTX, powinno fajnie działać

**Comment by DezerteR** [comment]
*Wymagane*
* zapamiętywanie pozycji trasy, z pewną gęstością tylko
* interpolacja zmiennych złączowych, ciekawe jak to wyjdzie
* wizualizacja z pozycji złaczowych

**Comment by DezerteR** [comment]
*Proponowane rozwiązanie:*
Zakładamy że w razie wystąpienia możliwości kolizji robot może zejść z zaznaczonej trasy. Pozwala nam to na następujące rozwiązanie:
* W zależności od tego co jest priorytetem: omijanie kolizji czy trzymanie się trasy
Możemy:
* zpróbkować trasę w kilku punktach pomiędzy kolizjami
* wyznaczyć bezkolizyjne położenia w tych punktach
* interpolacją złączową przjść pomiędzy tymi punktami
