### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by LazyFalcon** [LazyFalcon/Manipulator3D#15]
- [x]  ładowanie/przeładowywanie sceny: zczyszczenie wszystkiego postawienie nowego
- [x] przeglądarka plików: dla wyboru skryptów i scen: można zrobić po prostu listę widocznych
- [x] odświeżanie skryptów, możliwa automatyzacja tego, np co 5s reload zmian
- [ ] zapamiętywanie, wczytywanie wygenerowanych tras
- [ ] konsolka pythonowa
- [ ] eksport danych dla matlaba: prędkości, przyspieszenia, pozycje złaczowe, dane z grafów
  - [x] zmienić na zbieranie danych przez pythona
  - [x] zbieranie jPozycji robota
  - [x] zbieranie pozycji i orientacji efektora
  - [x] prędkości i przyspieszenia efektora
  - [x] info o ilości iteracji solvera w frame
  - [ ] dane z solvera: błąd, połozenie w trakcie iteracji
- [x] konfiguracja powyższego w pythonie
- [ ] ~~omijanie kolizji trasą~~
- [ ] ~~omijanie kolizji robotem~~
- [x] więcej władzy w pythonie
- [ ] wygładzanie ruchu w goTo robota
- [x] we are living in Amerika na budzik
- [x] blenderowy kursor
  - [x] globalna lista punktów, pochodzaca z kursora
  - [x] wyskakujące okienka z nazwą do edycji, nazwa znika po kliknięciu?
  - [x] zaznaczanie punktów z listy
  - [ ] wyświetlanie zaznaczonej listy, tak by zrobić z tego trasę
  - [x] dodawanie punktów z listy do aktualnie wybranego interpolatora -> proste
- [x] budowanie tras z tej listy
- [ ] bullet:
  - [ ] wyłączyć wpływ kolizji robota na otoczenie, jedynie customowy response
  - [ ] customowe responsy na kolizje
- [ ] interpolators
  - [ ] możliwość zmiany typu interpolatora w komendzie
  - [x] ruch po trasie złączowej
- [ ] RC::prev powinno cofać wszystkie stany :/, a przynajmniej pozycje robota
- [ ] łączenie interpolatorów krzywą hermite'a, wektory da się łatwo wyciągnąć
- [x] problem z przekazywaniem referencji do pythona
- [ ] proste kształty kolizyjne blender -> bullet
- [ ] export i przygotowanie convexShapów
- [ ] ładowanie sceny z pythona
- [ ] zapis i ładowanie wszystkich ustawień: sceny robota i innych pierdół
- [x] usprawnienie skryptu pytonowego
  - [x] niech przeciąganie sceny resetuje wszystkie stany
  - [x] natomiast przeciągnięcie pythona skutkuje wykonaniem przeciągniętego skryptu, na razie jedyna opcja, ?jak przekazać ref do RC, sceny? scopem?, ok!

**Comment by DezerteR** [comment]
Hmm, przy drag&dropie i py, to odpalać ten skrypt py jako jednorazowy czy jako główny? na razie jest jako główny, choć myślę że jednorazowy byłby lepszy

**Comment by DezerteR** [comment]
W pracy:
- [ ] Wstep, jakieś pierdu pierdu
- [ ] Motywacja
- [ ] Porównanie z istniejącymi
- [ ] Opis technologii
- [ ] Opis pracy z programem
- [ ]  Opis architektury, jak rozwiajć
- [ ] Teoria z części graficznej
  - [ ] O samej grafice 3D
  - [ ] Zastosowane efekty i ich opis
- [ ] Teroria z części robotycznej
  - [ ] Odnieśc się do inżynierki
  - [ ] Nowe rzeczy
- [ ] Pomiary wydajnościowe
- [ ] Porównanie z matlabem?
- [ ] Wykresy, wykresy, wykresy
- [ ] Przyszłe kierunki rozwoju appki
- [ ] Podsumowanie

**Comment by DezerteR** [comment]
Hmm, przy drag&dropie i py, to odpalać ten skrypt py jako jednorazowy czy jako główny? na razie jest jako główny, choć myślę że jednorazowy byłby lepszy

**Comment by DezerteR** [comment]
Meh, wybór głównego skryptu poprzez menu:
- wchodzimy: scene->chose main script i przeciągamy z folderu
- normalne przeciagnięcie skutkuje jednorazowym wykonaniem i zwolnieniem skryptu

**Comment by DezerteR** [comment]
Poprawić zachowanie edytora:
- [ ] X,Y,Z okazyjnie usuwają punkty :/
- [ ] merge ma jakieś fuckupy
- [ ] zrobić coś z automatycznym przypinaniem punktu do myszy

**Comment by DezerteR** [comment]
Proste cofanie akcji w edytorze? przynajmniej ze trzech

**Comment by DezerteR** [comment]
**Panel sterujący robotem !!!!!!!**
pozycją złączową, punktem docelowym, zapis i odczyt położenia!!!

**Comment by DezerteR** [comment]
- [ ] przydałaby się zmiana fov kamery podczas resizu

**Comment by DezerteR** [comment]
Hokay, TODO na ten weekend:
- [ ] ogarnąć customowe callbacki przy kolizjach
- [ ] wsparcie dla łapania obiektów
- [ ] save/load całej sceny i globalsów
- [ ] config parametrów symulacji pre akcja
- [ ] lekki rename szajsu
