### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by LazyFalcon** [LazyFalcon/Manipulator3D#2]
// cos jakby issues, bliższe todo list, do issues nie chce mi sie patrzec
- bullet
- lua
- joint interpolated movement
- teaching
- dodać czas do komend
- uogólnić interpolatory na zestawy {glm::vec4}, {vec4, quat}, {vector<double>}, najlepiej templatkowo, a odpowiednim
  kontenerom zapewnić odpowiednie operatory

==== joint interpolated movement ====
    konstruktor ma dwie opcje:
    - dostajemy zestaw wspóżednych zlaczowych i jestemy happy
    - dostajemy zestaw punktów, zlaczowe musimy sobie wyliczyc
    dodatkowo dostajemy zestaw modyfiaktorów predkosci
    interpolator sobie wybieramy

==== teaching =====
    co klatke zbieramy pozycje robota: vec4, quat i joint, w sumie to wystarczy joint, reszta jest wyliczalna
    przy pushu należy pamitać o tym żeby wygadzić punkty, albo można wykorzystać solver z lerpem do ledzenia pozycji
    punkt niech bdzie poruszany przez pointController z edytora, czemu wiec nie przeniesc by teachingu do 
    interpolatorów?

==== sledzenie trasy ====
    w kazdym frame wyliczamy o ile trzeba sie przemiecić, nastpnie zdejmujemy z interpolatora punkty aż przemieszczenie nie bedzie wieksze niz zakadane, potem można zinterpolować pomidzy punktami, ale po chuj?

==== commands ====
    wydzielic:
    - moveglm::vec4 interpolacja jedynie trasy kartezjańskiej, to co teraz jest
    - move<Point> interpolacja trasy 3D i kontrolowanie orientacji efektora
    - move<Joints> interpolacja zlaczowa
        Każdy z inna implementacja, tryzmajacy inny interpolator
    - goTo<vec4>
    - goTo<Point>
    - goTo<Joints>
    - wait - przerywa dziaanie na okrelony czas
    - waitOnSignal - przerywa czekajc na sygnal
    - waitIfSignal - czeka na czas lub sygnal
    - executeOnSignal - wykonuje rozkaz po dostaniu sygnalu, sygnaly sa w globalnym obiekcie Signals, sygnal może istniec do odebrania, badz jedna klatke
    - executeOnValue - definiujemu wasny operator porównania executeOn([&value]()bool->{return value > 20}, []{...})
    - 

```
commands sa tworzone przez builder na podstawie enuma/stringa, nastpnie parametryzowane, można je też jako do lua  wepchać()
```

==== Signals ====
    pierwsze 32 bity sa resetowane co klatke, pozostae sa czyszczone po odczycie
    {
        uint64_t data;
        void update(){
            data &= 0xffffffff00000000;
        }
        bool operator [](uint64_t i){
            bool out = data & i;
            if(i > 0xFFFFFFFF)
                data &= ~i;
            return out;
        }
    }

==== Ksztaty ====
    w sumie to po co?
    Przydalyby sie jakies predefiniowane ksztalty typu circle, arc, 
    - circle - (punkt, normalna, promień), (trzy punkty), (dwa punkty, normalna, promień)
    - arc (dwa punkty, normalna, promień, która czesc), (trzy punkty), (punkt, normalna, uk w katach)

==== Edytor ====
    zrobic obracanie grup punktów

==== ogólne ====
    graf ma defaultowy tryb LastX, trzeba mu zrobić opcje exportu danych dla matlaba
    dać możliwoć logowania wiekszej iloci danych

==== punkty ====
    mozliwosc zapisania pozycji robota {vec4, quat, vector<float>} do mapy/vectora, z menu, komendy savePoint()
    punkty te maja generyczne nazwy Px, 
    vector bedzie lepszy
    zrobic tak by dalo sie punkty wywietlic na 3D, jakos korzystac w interpolatorach, np goTo(point("P123")+glm::vec4(0,0,13));

==== zrobić w końcu klase Label bedaca const charem[] o staym rozmiarze, np. 30 znaków, 
    struct InfoLabel {
        char word[31];
        char size;
        InfoLabel(const char\* _word){
            std::copy(_word, strlen(_word), word);
        }
        InfoLabel(const string _word){
            std::copy(_word.begin(), _word.end(), word);
        }
        InfoLabel(const InfoLabel&) = delete;
        InfoLabel(const InfoLabel&&) = delete;
        InfoLabel& operator = (const InfoLabel&) = delete;  
    };
    powinno sie ladnie alignować.

==== Oswietlenie ====
    Dotyczy wszystkich projektów:
    deferred rendering jest i tak potrzebny, nie ma uja, potrzebuje glebokości i difusse, normalek już nie tak bardzo
    oświetlenie można zrobić kombinowane, dla kilku dużych swiata ze sceny można zrobić forward rendering, dobierając odpowiedni shader(dla ilosci swiatel), dzieki temu mamy możliwość odrysowania zaawansowanych materiałów,
    mamy też możliwość zrobić ladny spectacular, i może nie bdzie też takiego impaktu na odrysowanie tego

```
  dla małych świateł rysujemy deferred, uproszczony spectacular, wszystko uproszczone, ale za to tanie i ładne

tu coś ciekawego: http://www.gamedev.net/topic/669443-pbr-g-buffer-parameters-metalness/#entry5236508
* w przypadku TnS forward będzie słoneczko 
* w m-game wybierzemy dwa-trzy największe światła

Oprócz tego do TnS trzeba dodać noramal i spectacular testures, albo chodziarz specta, tak by ten czołg przestał wyglądać jak zabawka.

I cienie! to priorytet, przynajmniej jakie fejkowe globalne, albo od tych największych świateł.
Tylko będzie problem z cieniowaniem trawy, trawa musi być oświetlona i cieniowana w deferred.

No i dupa, słoneczka nie policzymy w forward przez głupią trawę, w sumie to dla globalnego światła jeden chuj gdzie to liczymy, wiec TnS może być fully deferred. 
Ale już mgrka może tak robić trzy największe światła liczymy forward, one też castuja cienie.

Cienie w TnS: global(orthogonal), w nocy od pointLights

warto już teraz rozważyć HDR, jeśli dzisiaj zrobię światła na ok
```

**Comment by DezerteR** [comment]
==== Oswietlenie ====
Dotyczy wszystkich projektów:
deferred rendering jest i tak potrzebny, nie ma uja, potrzebuje glebokości i difusse, normalek już nie tak bardzo
oświetlenie można zrobić kombinowane, dla kilku dużych swiata ze sceny można zrobić forward rendering, dobierając odpowiedni shader(dla ilosci swiatel), dzieki temu mamy możliwość odrysowania zaawansowanych materiałów,
mamy też możliwość zrobić ladny spectacular, i może nie bdzie też takiego impaktu na odrysowanie tego

  dla małych świateł rysujemy deferred, uproszczony spectacular, wszystko uproszczone, ale za to tanie i ładne

tu coś ciekawego: http://www.gamedev.net/topic/669443-pbr-g-buffer-parameters-metalness/#entry5236508
* w przypadku TnS forward będzie słoneczko 
* w m-game wybierzemy dwa-trzy największe światła

Oprócz tego do TnS trzeba dodać noramal i spectacular testures, albo chodziarz specta, tak by ten czołg przestał wyglądać jak zabawka.

I cienie! to priorytet, przynajmniej jakie fejkowe globalne, albo od tych największych świateł.
Tylko będzie problem z cieniowaniem trawy, trawa musi być oświetlona i cieniowana w deferred.

No i dupa, słoneczka nie policzymy w forward przez głupią trawę, w sumie to dla globalnego światła jeden chuj gdzie to liczymy, wiec TnS może być fully deferred. 
Ale już mgrka może tak robić trzy największe światła liczymy forward, one też castuja cienie.

Cienie w TnS: global(orthogonal), w nocy od pointLights

warto już teraz rozważyć HDR, jeśli dzisiaj zrobię światła na ok

**Comment by DezerteR** [comment]
==== Cienie ====
Robimy tylko dla największych świateł, TnS: słoneczko, Mgr: dwa największe, punktowe/

**Comment by DezerteR** [comment]
==== Links ====
!!!
https://learningcentral.sabanow.net/Saba/Web/Cloud
https://mail.google.com/mail/?tab=wm#inbox
https://sites.google.com/site/lteencyclopedia/lte-acronyms
http://reviews.emea.nsn-net.net/dashboard/?view=mine
http://krredmine01/redmine/rb/taskboards/399
https://bts.inside.nsn.com/twiki/bin/view/LTEeNB/CPlaneDevelopmentTeam
https://www.displayfusion.com/Features/Taskbar/
https://www.youtube.com/watch?v=x3h_L2j9-HA&list=RDzZpRVEZQGbk&index=9
https://www.google.fi/search?q=statistic+process+control&ie=utf-8&oe=utf-8&gws_rd=cr&ei=3qBZVb3VJoWosAWttYHQBg
http://frictionalgames.blogspot.fi/2012/09/tech-feature-hdr-lightning.html
http://gamedev.stackexchange.com/questions/53377/reinhard-tone-mapping-and-color-space
https://software.intel.com/en-us/articles/hdr-rendering-with-compute-shader-sample
https://software.intel.com/en-us/search/site/article/language/en/type/article?solrsort=ds_created%20desc
http://www.gamedev.net/topic/659042-post-process-order/?hl=hdr#entry5168628
http://www.gamedev.net/topic/658419-hdr-tonemapping-exposure-selection/?hl=hdr#entry5164892
http://wes-uoit-comp-graphics.blogspot.fi/2013/04/shaders-time-bloom-hdr.html
http://www.gamedev.net/topic/655835-whats-the-precondition-of-hdr-postprocess/?hl=hdr#entry5149221
http://www.gamedev.net/topic/658419-hdr-tonemapping-exposure-selection/?hl=hdr#entry5164892
http://www.heroesandgenerals.com/community/14126/clear-sky-to-overcast-from-a-rendering-perspective
http://www.kevinboulanger.net/grass.html
http://www.gamedev.net/topic/644199-hdr-adaption-delta-timestep/?hl=hdr#entry5069267
http://ogldev.atspace.co.uk/www/tutorial28/tutorial28.html
http://outerra.blogspot.cz/2012/05/procedural-grass-rendering.html
http://www.gamedev.net/topic/645080-good-way-to-manage-grass-rendering/?hl=%2Bgrass+%2Bculling#entry5075245
http://www.gamedev.net/page/resources/_/technical/game-programming/the-lua-tutorial-r2999
http://www.gamedev.net/page/resources/_/technical/game-programming/state-machines-in-games-r2982
https://molecularmusings.wordpress.com/2011/11/03/adventures-in-data-oriented-design-part-1-mesh-data-3/
http://www.slideshare.net/CassEveritt/approaching-zero-driver-overhead
https://www.youtube.com/watch?v=i-ThVrr5boY
https://www.youtube.com/watch?v=aI-i7iMWnYg&index=24&list=PLlllJ-D_6dedu_3gm5vwfYVWnKiKItM8S
http://q2a.emea.nsn-net.net/
http://accidentalnoise.sourceforge.net/docs.html
https://books.google.fi/books?id=_FnSBQAAQBAJ&pg=PA177&lpg=PA177&dq=Signed+CoC+radius&source=bl&ots=1OZGXswEVF&sig=cdmzO6sI1ZSoVudgK7J03ryZw7w&hl=pl&sa=X&ei=UNiHVb-rDsSJygOPipGIAQ&ved=0CCIQ6AEwAA#v=onepage&q=Signed%20CoC%20radius&f=false
http://developer.download.nvidia.com/shaderlibrary/webpages/hlsl_shaders.html
https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html
https://disney-animation.s3.amazonaws.com/library/s2012_pbs_disney_brdf_notes_v2.pdf
https://gamedevcoder.wordpress.com/2011/04/11/light-pre-pass-vs-deferred-renderer-part-1/
http://frictionalgames.blogspot.fi/2010/12/bye-bye-pre-pass-lighting.html
http://frictionalgames.blogspot.fi/2010/10/pre-pass-lighting-redux.html
http://www.gamedev.net/topic/669443-pbr-g-buffer-parameters-metalness/#entry5236508
http://www.slideshare.net/guest11b095/a-bit-more-deferred-cry-engine3
http://www.slideshare.net/TiagoAlexSousa/secrets-of-cryengine-3-graphics-technology
http://www.slideshare.net/naughty_dog/lighting-shading-by-john-hable

**Comment by DezerteR** [comment]
-----
drawTexturedBox 
może być obracany przez przeliczenie obrotu na CPU

**Comment by DezerteR** [comment]
ustaiwianie grafowi referencji/wskaźnika do sledzenia.
