### ISSUE TITLE
Only one global light

### ISSUE THREAD

**Issue by LazyFalcon** [LazyFalcon/Manipulator3D#3]
There should e only one global light, with ortho/perspective projection. Hardcoded, with little runtime configuration.
It could be pinned abowe users camera.

There would be one source casting global light with spectacular and all this shit.

Or maybe SSAO? when shadows are little crappy.

**Comment by DezerteR** [comment]
SSAO
----
http://www.gamedev.net/page/resources/_/technical/graphics-programming-and-theory/a-simple-and-practical-approach-to-ssao-r2753

**Comment by DezerteR** [comment]
http://www.slideshare.net/DICEStudio/shiny-pc-graphics-in-battlefield-3

**Comment by DezerteR** [comment]
https://books.google.fi/books?id=aG3y7WQGzmQC&pg=PA147&lpg=PA147&hl=pl#v=onepage&q&f=false

**Comment by DezerteR** [comment]
shadows fixes:
http://www.idevgames.com/forums/thread-1792.html

**Comment by DezerteR** [comment]
GL_R11F_G11F_B10F for HDR

**Comment by DezerteR** [comment]
coś o terenie
http://www.slideshare.net/DICEStudio/terrain-in-battlefield-3-a-modern-complete-and-scalable-system?related=1
