### ISSUE TITLE
Do poczytania

### ISSUE THREAD

**Issue by LazyFalcon** [LazyFalcon/Manipulator3D#7]
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.68.5669&rep=rep1&type=pdf

**Comment by DezerteR** [comment]
Trochę o planningu:
http://www1.cs.columbia.edu/~allen/F14/NOTES/trajectory.pdf
http://www.araa.asn.au/acra/acra2004/papers/shen.pdf

**Comment by DezerteR** [comment]
o ssao 
http://www.iquilezles.org/www/articles/sphereao/sphereao.htm

**Comment by DezerteR** [comment]
http://www.nvidia.com/object/siggraph-2008.html
